# Bag of Words, Stop Word Filtering & TF-IDF

1972022 - Sthefan Marley Tanza

## Bag of Words

Bag of Words menyederhanakan representasi text sebagai sekumpulan kata serta mengabaikan grammar dan posisi tiap kata pada kalimat. Text akan dikonversi menjadi lowercase dan tanda baca akan diabaikan.

### Dataset

In [46]:
corpus = [
    'Linux has been around since the mid-1990s.',
    'Linux distributions include the Linux kernel.',
    'Linux is one of the most prominent open-source software.'
]

corpus

['Linux has been around since the mid-1990s.',
 'Linux distributions include the Linux kernel.',
 'Linux is one of the most prominent open-source software.']

### Bag of Words model dengan CountVectorizer

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

vectorizer = CountVectorizer()
vectorized_X = vectorizer.fit_transform(corpus).toarray()
vectorized_X

array([[1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1]])

In [48]:
vectorizer.get_feature_names_out()

array(['1990s', 'around', 'been', 'distributions', 'has', 'include', 'is',
       'kernel', 'linux', 'mid', 'most', 'of', 'one', 'open', 'prominent',
       'since', 'software', 'source', 'the'], dtype=object)

### Euclidean Distance untuk mengukur jarak antar dokumen

In [49]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

distances = euclidean_distances(vectorized_X)

for i in range(len(distances)):
    for j in range(i, len(distances)):
        if i == j:
            continue
        jarak = distances[i][j]
        print(f'Jarak dokumen {i+1} dan {j+1}: {jarak}')

Jarak dokumen 1 dan 2: 3.1622776601683795
Jarak dokumen 1 dan 3: 3.7416573867739413
Jarak dokumen 2 dan 3: 3.4641016151377544


## Stop Word Filtering

In [50]:
corpus

['Linux has been around since the mid-1990s.',
 'Linux distributions include the Linux kernel.',
 'Linux is one of the most prominent open-source software.']

### Stop Word Filtering dengan CountVectorizer

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
vectorized_X = vectorizer.fit_transform(corpus).todense()
vectorized_X

matrix([[1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 1, 1, 1, 2, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 1, 1, 1]])

In [52]:
vectorizer.get_feature_names_out()

array(['1990s', 'distributions', 'include', 'kernel', 'linux', 'mid',
       'open', 'prominent', 'software', 'source'], dtype=object)

## TF-IDF (Term Frequency - Inverse Document Frequency)

TF-IDF (Term Frequency - Inverse Document Frequency) merupakan salah satu metode statistik yang digunakan untuk mengukur seberapa penting suatu kata terhadap suatu dokumen tertentu dari sekumpulan dokumen atau corpus.

In [53]:
corpus = [
    'the house had a tiny little mouse', 
    'the cat saw the mouse',
    'the mouse ran away from the house', 
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

corpus

['the house had a tiny little mouse',
 'the cat saw the mouse',
 'the mouse ran away from the house',
 'the cat finally ate the mouse',
 'the end of the mouse story']

### TF-IDF Weights dengan TfidfVectorizer

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


- Kolom pertama merupakan index dari kumpulan kata atau corpus.
- Kolom kedua merupakan index dari feature names yang dihasilkan dari bag of words.
- Kolom ketiga merupakan bobot dari setiap hasil yang dilakukan TfidfVectorizer.

In [55]:
vectorizer.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [56]:
response.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.4755751 , 0.58946308, 0.28088232, 0.        , 0.        ,
         0.        , 0.58946308],
        [0.        , 0.        , 0.58873218, 0.        , 0.        ,
         0.        , 0.        , 0.34771471, 0.        , 0.72971837,
         0.        , 0.        ],
        [0.        , 0.58946308, 0.        , 0.        , 0.        ,
         0.4755751 , 0.        , 0.28088232, 0.58946308, 0.        ,
         0.        , 0.        ],
        [0.58946308, 0.        , 0.4755751 , 0.        , 0.58946308,
         0.        , 0.        , 0.28088232, 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.67009179, 0.        ,
         0.        , 0.        , 0.31930233, 0.        , 0.        ,
         0.67009179, 0.        ]])

In [57]:
import pandas as pd

df = pd.DataFrame(response.todense().T, # T adalah transpose
                 index=vectorizer.get_feature_names_out(),
                 columns=[f'D{i+1}' for i in range(len(corpus))])

df

D1        D2        D3        D4        D5
ate      0.000000  0.000000  0.000000  0.589463  0.000000
away     0.000000  0.000000  0.589463  0.000000  0.000000
cat      0.000000  0.588732  0.000000  0.475575  0.000000
end      0.000000  0.000000  0.000000  0.000000  0.670092
finally  0.000000  0.000000  0.000000  0.589463  0.000000
house    0.475575  0.000000  0.475575  0.000000  0.000000
little   0.589463  0.000000  0.000000  0.000000  0.000000
mouse    0.280882  0.347715  0.280882  0.280882  0.319302
ran      0.000000  0.000000  0.589463  0.000000  0.000000
saw      0.000000  0.729718  0.000000  0.000000  0.000000
story    0.000000  0.000000  0.000000  0.000000  0.670092
tiny     0.589463  0.000000  0.000000  0.000000  0.000000